trigger:
  branches:
    include:
      - main
  paths:
    include:
      - openapi.yml

stages:
  - template: oas-base-pipeline.yml
    parameters:
      SpecificationFilePath: "DesignFirstOpenApi/openapi.yml"
      NugetPackageName: Luminis.Recipes.Server
      ClientNugetPackageName: Luminis.Recipes.API
      NPMPackageName: luminis-recipe-api
