openapi: "3.0.3"
info:
  title: Receptenboek API
  version: "3.0.0"
  contact:
    name: Tom Tiggeloven
    url: "https://linkedin.com/in/tom-tiggeloven"
    email: tom.tiggeloven@luminis.eu
servers:
  - url: https://localhost:7215
paths:
  #add recipe endpoint
  #get user endpoint
  #more recipe properties
  /recipes/{recipeId}:
    get:
      operationId: getRecipeById
      tags:
        - recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          $ref: "#/components/responses/recipeResponse"
        "204":
          description: No content
components:
  responses:
    recipeResponse:
      description: Recipe response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/recipeDto"
  schemas:
    recipeCreateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    recipeDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    userDto:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
