openapi: "3.0.3"
info:
  title: Receptenboek API
  version: "2.1.0"
  contact:
    name: Tom Tiggeloven
    url: "https://linkedin.com/in/tom-tiggeloven"
    email: tom.tiggeloven@luminis.eu
servers:
  - url: https://localhost:7215
paths:
  #add recipe endpoint
  #get user endpoint
  #more recipe properties
  /users/{userId}:
    get:
      operationId: getUserById
      tags:
        - users
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          $ref: "#/components/responses/userResponse"
        "204":
          description: No content
  /recipes:
    post:
      operationId: addRecipe
      tags:
        - recipes
      requestBody:
        $ref: "#/components/requestBodies/recipeCreateBody"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/recipeDto"
  /recipes/{recipeId}:
    get:
      operationId: getRecipeById
      tags:
        - recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          $ref: "#/components/responses/recipeResponse"
        "204":
          description: No content
components:
  requestBodies:
    recipeCreateBody:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/recipeCreateDto"
  responses:
    recipeResponse:
      description: Recipe response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/recipeDto"
    userResponse:
      description: User response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/userDto"
  schemas:
    recipeCreateDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    recipeDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    userDto:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
